version: 2.1
orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.1-node
        environment:
          PG_HOST: localhost
          PG_USER: postgres
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:12.8
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: soils_ag_wx_test
          POSTGRES_PASSWORD: 'password'
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Set up database
          command: bundle exec rails db:setup
      - run:
          name: Run tests
          command: bundle exec rake test
